# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BSA_MainGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.addFilesButton = QtWidgets.QPushButton(self.centralwidget)
        self.addFilesButton.setObjectName("addFilesButton")
        self.gridLayout_3.addWidget(self.addFilesButton, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.clearTableButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearTableButton.setObjectName("clearTableButton")
        self.gridLayout_3.addWidget(self.clearTableButton, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.closeAppButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeAppButton.setObjectName("closeAppButton")
        self.gridLayout_3.addWidget(self.closeAppButton, 0, 4, 1, 1)
        self.simpleIVplotWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.simpleIVplotWidget.setObjectName("simpleIVplotWidget")
        self.filesTab = QtWidgets.QWidget()
        self.filesTab.setObjectName("filesTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.filesTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWithFiles = QtWidgets.QTableWidget(self.filesTab)
        self.tableWithFiles.setObjectName("tableWithFiles")
        self.tableWithFiles.setColumnCount(0)
        self.tableWithFiles.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWithFiles, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.filesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.consoleOutput = QtWidgets.QPlainTextEdit(self.groupBox)
        self.consoleOutput.setObjectName("consoleOutput")
        self.gridLayout.addWidget(self.consoleOutput, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.simpleIVplotWidget.addTab(self.filesTab, "")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.plotTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.plotTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.plotTab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.plotTab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.plotTab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.plotWidget = QChartView(self.splitter)
        self.plotWidget.setObjectName("plotWidget")
        self.simplePVplotWidget = QChartView(self.splitter)
        self.simplePVplotWidget.setObjectName("simplePVplotWidget")
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.simpleIVplotWidget.addTab(self.plotTab, "")
        self.gridLayout_3.addWidget(self.simpleIVplotWidget, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.simpleIVplotWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addFilesButton.setText(_translate("MainWindow", "Add files ..."))
        self.clearTableButton.setText(_translate("MainWindow", "Clear table"))
        self.closeAppButton.setText(_translate("MainWindow", "Close App"))
        self.groupBox.setTitle(_translate("MainWindow", "Console Output"))
        self.simpleIVplotWidget.setTabText(self.simpleIVplotWidget.indexOf(self.filesTab), _translate("MainWindow", "Files"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.simpleIVplotWidget.setTabText(self.simpleIVplotWidget.indexOf(self.plotTab), _translate("MainWindow", "Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

from PyQt5.QtChart import QChartView
